### ISSUE TITLE
Compilation error w/ gcc-8.1

### ISSUE THREAD

**Issue by unclejimbo** [GameFoundry/bsf#174]
Here's the error message:

```
Building CXX object Source/Foundation/CMakeFiles/bsf.dir/bsfUtility/Utility/BsDynLibManager.cpp.o
In file included from /usr/include/c++/8.1.1/map:60,
                 from /home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Prerequisites/BsStdHeaders.h:22,
                 from /home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Allocators/BsStackAlloc.h:9,
                 from /home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Allocators/BsMemoryAllocator.h:443,
                 from /home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Prerequisites/BsPrerequisitesUtil.h:262,
                 from /home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Utility/BsDynLibManager.h:5,
                 from /home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Utility/BsDynLibManager.cpp:3:
/usr/include/c++/8.1.1/bits/stl_tree.h: In instantiation of ‘class std::_Rb_tree<bs::NativePtr<bs::DynLib>, bs::NativePtr<bs::DynLib>, std::_Identity<bs::NativePtr<bs::DynLib> >, std::less<void>, bs::StdAlloc<bs::NativePtr<bs::DynLib>, bs::GenAlloc> >’:
/usr/include/c++/8.1.1/bits/stl_set.h:133:17:   required from ‘class std::set<bs::NativePtr<bs::DynLib>, std::less<void>, bs::StdAlloc<bs::NativePtr<bs::DynLib>, bs::GenAlloc> >’
/home/unclejimbo/Devtools/bsf-1.0.0b/Source/Foundation/bsfUtility/Utility/BsDynLibManager.h:37:34:   required from here
/usr/include/c++/8.1.1/bits/stl_tree.h:452:21: error: static assertion failed: comparison object must be invocable with two arguments of key type
       static_assert(__is_invocable<_Compare&, const _Key&, const _Key&>{},
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Source/Foundation/CMakeFiles/bsf.dir/build.make:141: Source/Foundation/CMakeFiles/bsf.dir/bsfUtility/Utility/BsDynLibManager.cpp.o] Error 1

```

Meanwhile clang-6.0 will also generate similar errors regarding the invocability in stl_tree.h

Possible same issue and fix: https://bugzilla.redhat.com/show_bug.cgi?id=1541688

**Comment by jonesmz** [comment]
Well that is just *super* annoying. It's working fine on gcc 6.4 and 7.3, and VS2017.

It looks like the fix is that the comparison function needs to be in the header file. But the whole point was to have it be hidden in the cpp file.

**Comment by BearishSun** [comment]
GCC 8.2 appears to compile the code fine. I've yet to test Clang.

**Comment by BearishSun** [comment]
Clang 7 also appears to work fine as well. I'm going to assume this was an issue with that particular issue of the compiler itself and was since resolved. Closing but let me know if it's still causing issues and I'll reconsider.
